kind: pipeline
name: linux

workspace:
  base: /go
  path: src/github.com/meltwater/secretary

steps:
- name: build
  image: golang:1.9.2
  commands:
  - make

# Deploy executables to Github release tags
- name: github_release
  image: plugins/github-release
  secrets: [ github_token ]
  files: secretary-Linux-x86_64
  when:
    event:
    - tag

# Code coverage using https://codecov.io/github/mikljohansson/secretary
- name: codecove.io
  when:
    status:
    - success
  image: alpine:3.7
  commands:
  - bash <(curl -s https://codecov.io/bash)

---

kind: pipeline
name: darwin

workspace:
  base: /go
  path: src/github.com/meltwater/secretary

steps:
- name: build
  image: golang:1.9.2
  commands:
  - make tools
  - make deps
  - make fmt
  - make build GOOS=darwin OS=Darwin

# Deploy executables to Github release tags
- name: github_release
  image: plugins/github-release
  secrets: [ github_token ]
  files: secretary-Darwin-x86_64
  when:
    event:
    - tag
