kind: pipeline
name: linux

workspace:
  base: /go
  path: src/github.com/meltwater/secretary

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: build
  image: golang:1.9.2
  commands:
  - make

- name: test
  image: golang:1.9.2
  commands:
  - make test
  - make lint

# Code coverage using https://codecov.io/github/mikljohansson/secretary
- name: codecove.io
  when:
    status:
    - success
  image: alpine:3.7
  commands:
  - curl -o codecov.sh -s https://codecov.io/bash
  - chmod +x codecov.sh
  - ./codecov.sh

# Deploy executables to Github release tags
- name: github_release
  image: plugins/github-release
  secrets: [ github_token ]
  files: secretary-Linux-x86_64
  when:
    status:
    - success
    event:
    - tag

---

kind: pipeline
name: darwin

workspace:
  base: /go
  path: src/github.com/meltwater/secretary

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: build
  image: golang:1.9.2
  commands:
  - make OS=darwin

# Deploy executables to Github release tags
- name: github_release
  image: plugins/github-release
  secrets: [ github_token ]
  files: secretary-Darwin-x86_64
  when:
    status:
    - success
    event:
    - tag
